### ISSUE TITLE
Don’t create files multiple times

### ISSUE THREAD

**Issue by FlashHit** [Imposter/vscode-lua-vu#15]
Instead of creating the fb files 3 times, just create them one time and use them for all 3 folders/workspaces.

**Comment by FlashHit** [comment]
Cache the vext files, and class, json & vector files.
So we don’t need to download them for every project. We just download them once and done. Once in a while we can update them I guess. I think this would speed it up a lot.

also move the intermediate files to the root. Because otherwise vu will compile these files as well when starting up a server.

**Comment by FlashHit** [comment]
So for all folders: lib(class,json,vector) and types(shared,fb) 
For client: types(client)
For server: types(server)

they should be cached somewhere outside of the project.

the intermediate files should be in the root project folder.

**Comment by Imposter** [comment]
This approach would require specification of libraries for each Workspace folder independent of the other folders in the workspace. This is not currently possible with sumneko's extension as `Lua.workspace.library` can only be set once by the `project.code-workspace` and not individually in the folders' `.vscode/settings.json` files

The alternative (current approach) is currently blocked by https://github.com/EmulatorNexus/VeniceUnleashed/issues/730

**Comment by Imposter** [comment]
As discussed, the ideal approach can work by reordering the settings.json files.

**Comment by Imposter** [comment]
Fixed in a3696b76eca2a7c7e500447d0cf53d256b694543
