### ISSUE TITLE
table classes cause errors

### ISSUE THREAD

**Issue by FlashHit** [Imposter/vscode-lua-vu#16]
```lua
---@class Test
local Test = {}
```
This is causing an error.

![grafik](https://user-images.githubusercontent.com/56718716/146086905-68de03b4-f393-48d6-8143-d79040116ce6.png)

**Comment by Imposter** [comment]
This will require some rather large changes to the Lua parser. I'll work on this along with the other changes related to class usage optimizations. This approach would be to use 3rd-party plugin support in Sumneko's extension and using regular expressions to perform class-based intellisense hinting.

**Comment by Imposter** [comment]
We're not using the 3rd-party plugins for parsing. The existing parser will be updated.

**Comment by Imposter** [comment]
Fixed in cf1e61b75adc5f5e257b7fbe8b4aa20954225ff9
