### ISSUE TITLE
Use generic annotation for GetSettings

### ISSUE THREAD

**Issue by FlashHit** [Imposter/vscode-lua-vu#18]
Use `—-@generics` for `ResourceManager:GetSettings(string: Setting)`

So for example if I do `local s_GameSettings = ResourceManager:GetSettings("GameSettings")` it would automatically identify it as `GameSettings`

**Comment by Imposter** [comment]
This should be possible. I'll add the ability to add hooks to the extension (code generator) so we can add VU specific stuff there. I may work on this for Version 1.0 release if time permits.

**Comment by Imposter** [comment]
For more information: https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations#generic
