### ISSUE TITLE
Add the mod.json to the project

### ISSUE THREAD

**Issue by FlashHit** [Imposter/vscode-lua-vu#19]
Atm the projects don’t include the mod.json. Would be cool to be able to edit it aswell.

**Comment by FlashHit** [comment]
Maybe even the webui folder

**Comment by Imposter** [comment]
Added in https://github.com/Imposter/vscode-lua-vu-template/commit/71f17c785797fdb138ec3492949f65b5f9b5cdaf

**Comment by Imposter** [comment]
A more detailed step will be included in the project wizard to address this

**Comment by Imposter** [comment]
I want to add, due to limitations of workspaces, we cannot add mod.json to the workspace. Unless we add the root folder, which is redundant. In the future, a command to open an editor for mod.json may be considered.

**Comment by Imposter** [comment]
Added in 76d387a
