### ISSUE TITLE
Canceling new project creation isn't working

### ISSUE THREAD

**Issue by FlashHit** [Imposter/vscode-lua-vu#20]
If you create a new project with vua it will ask for the mod name and then for the location/path. Then it says Enter to go on and ESC to abort/ cancel it, but it isn't working. If I press ESC it will still create the project. If I just minimize the window or whatever it will also create the project. So there is no way to cancel it.
The issue is that I have to enter the whole location address `C:\Users\%User%\Documents\Battlefield 3\Server\Admin\Mods\<Your Mod Name>`. So I would also suggest that the address that it is currently using is editable, so I don't have to write the whole path. Or at least let me minimize to copy the address from the window explorer.

**Comment by Imposter** [comment]
Fixed in 0392224
