### ISSUE TITLE
Add support for nestedArrays, nestedTables and operators

### ISSUE THREAD

**Issue by Imposter** [Imposter/vscode-lua-vu#21]
The VU-Docs have nestedArrays, nestedTables and operators which are not currently implemented (or figured out) for the EmmyLua equivalent in the meta files.

This is required to finish up most of the VEXT related stuff for the 1.0 release.

**Comment by FlashHit** [comment]
Example: https://docs.veniceunleashed.net/vext/ref/server/type/player/#weaponunlocks
It’s just that you can do .weaponUnlocks[1][1] and it would give you the weaponunlock for the weapon of slot 1. 
Like each weapon has 4 unlocks i think.
So just doing weaponUnlock[1] would return a table or nil.

**Comment by FlashHit** [comment]
Maybe sth like this?
```
code += `table<integer, vector|${_LT(p.type)}[]>`; // nestedTable

code += `vector|table<integer, vector|${_LT(p.type)}[]>`; // nestedArray (who cares, doesn’t even exist)
```

**Comment by FlashHit** [comment]
And operators are not possible atm I guess: https://github.com/sumneko/lua-language-server/issues/599

**Comment by Imposter** [comment]
Fixed in https://github.com/Imposter/vscode-lua-vu/pull/32
