### ISSUE TITLE
Update existing project

### ISSUE THREAD

**Issue by FlashHit** [Imposter/vscode-lua-vu#25]
Maybe it would be nice to update an project. this would basically just override the project.workspace and all .vscode/settings.

Most use just the mod folder instead of a workspace/project. So maybe even that should work. So it would create a project.workspace and all .vscode/settings. And then close the folder and open the project.

**Comment by Imposter** [comment]
The alternative is to create a new project and copy all the code over it. I think it might be too complex to make these changes via code.

**Comment by Imposter** [comment]
Closing this. It doesn't seem to be very important.
