### ISSUE TITLE
Use $APPDATA for library location

### ISSUE THREAD

**Issue by FlashHit** [Imposter/vscode-lua-vu#29]
Instead of: `c:/users/admin/appdata/roaming/` you can just do `$APPDATA/`.

**Comment by FlashHit** [comment]
Maybe it would make sense to add it to the template repository directly.

**Comment by Imposter** [comment]
This was done in https://github.com/Imposter/vscode-lua-vu-template/commit/9c6bfc49f985da933f0b001d6051fe0c223784ff
