### ISSUE TITLE
Unable to download content after VSCode update

### ISSUE THREAD

**Issue by paulhobbel** [Imposter/vscode-lua-vu#31]
It seems like a recent VSCode update broke the content downloader of Vua

![image](https://user-images.githubusercontent.com/20015650/164892312-d53ac804-61df-4ba0-bf86-682bd996bc1c.png)

I'm running on VSCode 1.66.1

**Comment by Imposter** [comment]
This issue is related to https://github.com/microsoft/vscode/issues/147807. I don't know why Microsoft recommended using this extension if it was unmaintained. I'll write a downloader class for this. Thanks for the find.

**Comment by Imposter** [comment]
Should be fixed in [fd6b929](https://github.com/Imposter/vscode-lua-vu/commit/fd6b92919f9bfb88df03bd174c5ab5e8a4452002). Please re-open if the issue persists.

v0.3.3 will contain the fix for this, it has been pushed to the marketplace.

**Comment by paulhobbel** [comment]
Works, sorry couldn't check before, thanks for the quick fix
