### ISSUE TITLE
[Req] Support events and hooks

### ISSUE THREAD

**Issue by FlashHit** [Imposter/vscode-lua-vu#39]
Like this:
https://github.com/sumneko/lua-language-server/issues/865

using:
https://github.com/EmulatorNexus/VU-Docs/tree/master/types/shared/event
And:
https://github.com/EmulatorNexus/VU-Docs/tree/master/types/shared/hook

Note: these are just links to the shared events and hooks. There are client and server specific ones as well.

**Comment by Imposter** [comment]
This has been completed in code and will be released with v0.3.6.
