### ISSUE TITLE
Vua fails to download documentation

### ISSUE THREAD

**Issue by paulhobbel** [Imposter/vscode-lua-vu#9]
When downloading and building the documentation content Visual Studio Code returns the following error:
![image](https://user-images.githubusercontent.com/20015650/126037055-515ebcfa-a512-4186-b00a-d2c988ac88d7.png)

**Comment by FlashHit** [comment]
Did you download it here or via VSCode marketplace?

**Comment by paulhobbel** [comment]
via the VSCode marketplace. I think I found out whats going on btw. It seems to happen when it renames data-temp ->data

**Comment by paulhobbel** [comment]
If I pause execution, rename data-temp -> data and then add the .complete file it works fine

**Comment by Imposter** [comment]
This was an issue due to the way writeFile was called, rather than providing a string/bytes like object, an object was passed. This has been corrected and a new update has been pushed v0.2.10.
